name: E2E Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  FIXA-E2E-TESTS:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-jammy
      # Using the official Microsoft Playwright Docker container with root permissions for GitHub Actions compatibility
      options: --ipc=host
    
    # Add concurrency to prevent multiple workflows running simultaneously
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install dependencies
      run: |
        # Install dependencies using clean install
        npm ci
        # No need to install browsers as they are pre-installed in the container
      
    - name: Create env file
      run: |
        touch .env
        echo "FIXA_USERNAME=${{ secrets.FIXA_USERNAME }}" >> .env
        echo "FIXA_PASSWORD=${{ secrets.FIXA_PASSWORD }}" >> .env
        
    - name: Run Playwright tests
      run: npx playwright test
      
    - name: Install Java in container
      if: always()
      run: |
        apt-get update
        apt-get install -y openjdk-17-jre-headless
        
    - name: Clear previous Allure results
      if: always()
      run: |
        rm -rf allure-results/* || true
        rm -rf allure-report/* || true
        
    - name: Generate Allure Report
      if: always()
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        npx allure generate allure-results --clean
        echo "Report generated at $(date)" > allure-report/generated.txt
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          playwright-report/
          test-results/
          logs/
          allure-results/
          allure-report/
        retention-days: 30
        compression-level: 6
        
    - name: Deploy Allure Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAGES_TOKEN }}
        publish_dir: allure-report
        publish_branch: gh-pages
        force_orphan: true
        full_commit_message: 'Deploy Allure report to GitHub Pages [skip ci] - ${{ github.sha }}'
        enable_jekyll: false
        cname: ''  # Ensures no caching issues with custom domains
