name: E2E Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  FIXA-E2E-TESTS:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-jammy
      # Using the official Microsoft Playwright Docker container with root permissions for GitHub Actions compatibility
      options: --ipc=host
    
    # Add concurrency to prevent multiple workflows running simultaneously
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install dependencies
      run: |
        # Install dependencies using clean install
        npm ci
        # No need to install browsers as they are pre-installed in the container
      
    - name: Create env file
      run: |
        touch .env
        echo "FIXA_USERNAME=${{ secrets.FIXA_USERNAME }}" >> .env
        echo "FIXA_PASSWORD=${{ secrets.FIXA_PASSWORD }}" >> .env
        
    - name: Run Playwright tests
      run: npx playwright test
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: |
          playwright-report/
          test-results/
          logs/
        retention-days: 30
        compression-level: 6 # New feature in v4 for better compression
