name: E2E Tests

on:
  push:
    branches: [ master ]
    paths:
      - '**.ts'
      - '**.js'
      - 'package*.json'
      - '.github/workflows/**'
  pull_request:
    branches: [ master ]
    paths:
      - '**.ts'
      - '**.js'
      - 'package*.json'
      - '.github/workflows/**'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  FIXA-E2E-TESTS:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    
    # Prevent redundant workflow runs
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number || github.sha }}
      cancel-in-progress: true
    
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-jammy
      options: --ipc=host --shm-size=2gb
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Setup Node.js and cache
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit
      
    - name: Setup environment variables
      run: |
        cat << EOF > .env
        FIXA_USERNAME=${{ secrets.FIXA_USERNAME }}
        FIXA_PASSWORD=${{ secrets.FIXA_PASSWORD }}
        EOF
      
    - name: Run Playwright tests
      run: npx playwright test --workers=2
      env:
        CI: 'true'
        NODE_ENV: 'test'
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ github.sha }}
        path: |
          playwright-report/
          test-results/
          logs/
        retention-days: 14
        compression-level: 9
        if-no-files-found: error
